### PR TITLE
update admin interface for django 2

### PR DESCRIPTION
**Pull request by julzhk**
Django 2 uses mark_safe for html in admin interface

### CODE REVIEW

**Comment by ludrao** [comment]
Hi @julzhk, could you elaborate why you needed to rewrite step 4 of the migration?
Also do you have a way to test against earlier versions of Django (i.e. <2.0)
Thx!

**Comment by julzhk** [comment]
Hi 
I was surprised too - I had a 'migrations clash' error when I attempted to install. 
I can't remember my exact install sequence - maybe there was a partial migration... but recreating the migration worked as you can see. I'm using sqlite locally btw.

Re: tests - good question. 
And it'd be a bit ugly to put version-conditionals around this rendering.

**Comment by JackAtOmenApps** [comment]
Please merge this. Seeing the raw html in admin is frustrating.

**Comment by ludrao** [comment]
Sorry for the long delay. @julzhk or @OmenApps would you be able to check if the migration script works? Especially as I merged another PR that changed them.

**Comment by danihodovic** [comment]
@ludrao can this be merged?

**Comment by ludrao** [comment]
Hi @danihodovic, I'd like to, but reading back the thread there is an un-answered question. It's a long time ago now, but I am unsure of why migration step 4 was changed and if this not going to cause migration issue for people upgrading.
Would you be able to test it? (install the released version and then upgrade with this version and see how it goes). Thx.

**Comment by danihodovic** [comment]
I'm running this branch on https://findwork.dev with Django 2.2.

**Comment by RaphaelKimmig** [comment]
@ludrao Can this be closed? From what i gather master has already been fixed?

**Comment by ludrao** [comment]
Per @RaphaelKimmig  closing this issue. Thx!

**Pull request closed without merging**
