### PR TITLE
Run tests on commit

### LINKED ISSUE #52: Run tests on commit
Noticed my PR wasn't running tests.  Can we set up automated CI - github actions or something?  Would make contributions easier

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes #52

### CODE REVIEW

**Comment by thenewguy** [comment]
This runs all the tests.  Some are failing.  The ones that are failing are very old. I suggest dropping them and removing compatibility code

**Comment by thenewguy** [comment]
Also, I got it working running setup.py.  Encountered some troubles with the newer packaging configuration.  That needs to be investigated if you want to go that route, but this gets it working

**Comment by ludrao** [comment]
I push some changes I had locally to support cfg+tox. (minor changes)

**Comment by thenewguy** [comment]
Ok - I will close and re-open once https://github.com/thenewguy/django-tellme/tree/build-feedback is working as intended.  Idea is to build javascript with webpack and then build the sdist with tox

**Comment by ludrao** [comment]
Haha I was trying to merge your code in :)
I get a "InterpreterNotFound' when I tried to run tox with your tox.ini

**Comment by ludrao** [comment]
I was thinking that it might be better to fix tox so we can add github action as you proposed in this PR. I liked the publish one :)

**Pull request closed without merging**
