### PR TITLE
removed sdistsrc in favor of --installpkg to simplify local testing

### LINKED ISSUE #63: Tox broken for local testing
The new test flow from #61 make it difficult to run tests locally due to requiring a prebuilt sdist.

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes #63

### CODE REVIEW

**Comment by ludrao** [comment]
That just worked out great :+1: 
Out of curiosity what tool do you use to get several version of python installed (to run the matrix test) ? pyenv?

**Comment by thenewguy** [comment]
@ludrao it was a feature of github actions - you have to use their scripts

**Comment by ludrao** [comment]
No, sorry I meant on your local machine.

**Comment by thenewguy** [comment]
@ludrao [vagrant is my favorite](https://www.vagrantup.com/). My second choice is [docker](https://docs.docker.com/get-started/) but it isn't as convenient for my development workflow.

**Pull request merged**
