### PR TITLE
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy()

### PR DESCRIPTION
**Pull request by agusmakmun**

### CODE REVIEW

**Comment by ludrao** [comment]
Thx!

**Comment by NielkS** [comment]
hi @ludrao,
would it be possible to publish a new version that includes this change ?

**Comment by agusmakmun** [comment]
@ludrao any update for the newest version for this? Because I saw the latest version updated Jan 20, 2022.

**Comment by cbugot-swi** [comment]
The only change is just a warning, should not be blocking? I am not adding anything to this project anymore.
I'll look into (maybe not just now, might take a couple of weeks).

**Comment by ludrao** [comment]
The only change is just a warning, should not be blocking? I am not adding anything to this project anymore.
I'll look into (maybe not just now, might take a couple of weeks).

**Comment by agusmakmun** [comment]
@ludrao what about also add this new fields? https://github.com/ludrao/django-tellme/issues/71

So, the expectation is, when user reporting a bug & we solved it, then we can mark it as solved.

**Pull request merged**
