### PR TITLE
Opt email

### PR DESCRIPTION
**Pull request by Basiczombie**
Created in models.py an email field called email for non user email.

In the view I added an IF statement that checks for the user.id. IF found then adds user.id to the saved form else uses the POST email data.

In the feedback.js I added an IF statement that checks for a value in the new #feedback-user-email input and IF found passes along the submitters email.

In the template tpl-description.html I added a {% if not user.is_authenticated %} around the email input and accompanying <p>

In the admin I added the email to the list_display

### CODE REVIEW

**Comment by ludrao** [comment]
Hi @Basiczombie, thx for your contribution!
There seems to be IDE (Or Mac) left over files: .DS_Store, could you remove them from this pull request?
Also why do you need to modify html2canvas.js ? If not necessary I would recommend to restore the original file.
About feedback.js, this is comming from third 3rd. Usually I do not like to modifu 3rd party files but in the current case the upstream project seems to be inactive, so we may not have a choice here :-/
However the files should be minified. Usually you do not modify directly the minified version, but rather the source version (i.e. https://github.com/ivoviz/feedback/blob/master/development/feedback.js).
What I could propose: take the source version above, add it to this repository, and compile the minified version from it.
Would that work for you ?

**Comment by Basiczombie** [comment]
I had to unminify to be able to read the files and when sharing in the pull
to insure you were able to see the changes. I will take out the .DS_Store
as I thought that it was ignored, it is on my dev server, but I was using
local. The change to html2canvas was just an unminify so I could see how it
related in the calls I was unaware at the time it was 3rd party having
never worked with it before. feedback is your feedback.min.js I forgot to
add the min. I will work to make the changes.

**Comment by Basiczombie** [comment]
I believe that is all the changes you requested.

**Comment by ludrao** [comment]
HI @Basiczombie .
Thx for doing it real quick :) Unfortunately you added some other IDE related files (see .idea/)
Also you changed the html2canvas version, could you just revert it to the version before your changes ? (unless you had an issue with the original one)

**Comment by Basiczombie** [comment]
Have removed .idea/. I changed IDE's as Atom was giving me issues it seems PyCharm adds this folder. The html2canvas is the same development version that was stored with feedback.js. I can revert it to what you have in master if that would help.

**Comment by Basiczombie** [comment]
html2canvas should now match the version in master.

**Comment by ludrao** [comment]
Yes indeed, the one from feebackjs had a bug, and I had to pull a more recent version.
Thx for doing the requested changes.
I'll merge the PR now, but do not have much time to test it from master. If you have a chance to update the code from the merged master and test it, please let me know if it works as expected.
Thx!

**Comment by Basiczombie** [comment]
I installed the changes and tested it on my development site. It was working when I made the pull request.

**Comment by ludrao** [comment]
Ok, thx for your help. I'll do a release in a few days.

**Comment by peterfarrell** [comment]
@ludrao We'd love a release if you have time.

**Comment by ludrao** [comment]
Release done, 0.6.4. Thx to all contributors!

**Pull request merged**
