### PR TITLE
Feature/trans ja

### PR DESCRIPTION
**Pull request by salexkidd**
create translation for japanese.

### CODE REVIEW

**Comment by ludrao** [comment]
Thank you @salexkidd.
Can you run a double test on the master branch with your changes. When you are ok, let me know if you want me to do a minor release of the package so that the latest package on pypi contains the japanese translation.

**Comment by salexkidd** [comment]
OK, I'll test master brand. Please wait :)

**Comment by salexkidd** [comment]
@ludrao I'm tested now. Looking good! Thx Merging!

**Comment by ludrao** [comment]
OK. I'll do a release sometime next week. Ping me if you do not see it
coming :)

**Comment by salexkidd** [comment]
I thank you for @llann and @ludrao  work! :) Thx!!

**Comment by ludrao** [comment]
Hi @salexkidd, I just pushed the new release onto Pypi: https://pypi.python.org/pypi/django-tellme/0.6.3.
You should be able to pull it from your regular Python installer. Thx for your translation!

**Pull request merged**
