### PR TITLE
Added a DB index to Feedback.created

### PR DESCRIPTION
**Pull request by ZuluPro**
**This PR comes after #26** 

I also added `date_hierarchy` in Modeladmin.

### CODE REVIEW

**Comment by ludrao** [comment]
You seems to be much more knowledgeable than me on this :). Just curious why do you need this change ?

**Comment by ZuluPro** [comment]
Hello @ludrao 

The database index is like a separated table just for the index file.
It has the advantage of:
- Faster filter on this field
- Faster order_by on this field

I generally put an index on fields I know I will filter/order often. And always an index on DateTimeField.

And this performance plus will help with the `ModelAdmin.date_hierarchy`. ;)

**Comment by ZuluPro** [comment]
Please, let me rebase this branch before merge it.

**Comment by ludrao** [comment]
ok no prb, I'll wait for your rebase.

**Comment by ZuluPro** [comment]
Sorry for my latency, I rebased ;)

**Pull request merged**
