### PR TITLE
Implement internationalization (i18n)

### PR DESCRIPTION
**Pull request by llann**
I saw it was one of your todo, so here is the internationalization with French language included :)

### CODE REVIEW

**Comment by llann** [comment]
Btw I moved all the translation system to Transifex : https://www.transifex.com/django-tellme/django-tellme/

I let you define the process you want to use for user to translate in new languages in the Readme.md

If you have an account on Transifex, I can add you as owner and leave the projet as owner and just stay French coordinator.

**Comment by ludrao** [comment]
Merci llann!

That is a great contribution, I'll try merge it fast. I am not very familiar with i18n/l10n, so I'd first like to try it and see how that works.

I have one early comment though: In order to provide translation in the JS part, you had to modify feedback.js file. With the current state of the plugin I guess there was not so much of a choice. However I'd like to investigate an alternative without having to modify that file (reason: this file is from a separate/external project, and I'd like to be able to update it without having to do a merge)
The idea would be that django-tellme would provide a template that would itself call the 'feedback' js function providing the tpl variable that include the i18n calls.

Or do you have another idea?

**Comment by ludrao** [comment]
Hum it also missed the javascript_catalog view for the javascript translations. I am adding that in the urls.py file so the user does not have to deal with that.

**Comment by ludrao** [comment]
Il also bumped the version number and uploaded it on pypi

**Comment by llann** [comment]
Thanks you've done a great job in addition of my initial MR :) Plugin is a lot better like this :)

**Comment by ludrao** [comment]
BTW, I did not update the transifex thing (I am not familiar with it). If you want I'll let you deal wit it :)

**Pull request merged**
